#
# Autogenerated by Thrift
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
package Net::Cassandra::BackendConstants;
require 5.6.0;
use strict;
use warnings;
use Net::Cassandra::Backend::Thrift;


use constant VERSION => "3.0.0";

1;
